/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppNewApplicationRouteImport } from './routes/_app.new-application'
import { Route as AppMyApplicationsRouteImport } from './routes/_app.my-applications'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNewApplicationRoute = AppNewApplicationRouteImport.update({
  id: '/new-application',
  path: '/new-application',
  getParentRoute: () => AppRoute,
} as any)
const AppMyApplicationsRoute = AppMyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-applications': typeof AppMyApplicationsRoute
  '/new-application': typeof AppNewApplicationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-applications': typeof AppMyApplicationsRoute
  '/new-application': typeof AppNewApplicationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/my-applications': typeof AppMyApplicationsRoute
  '/_app/new-application': typeof AppNewApplicationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/my-applications' | '/new-application'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/my-applications' | '/new-application'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/my-applications'
    | '/_app/new-application'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/new-application': {
      id: '/_app/new-application'
      path: '/new-application'
      fullPath: '/new-application'
      preLoaderRoute: typeof AppNewApplicationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-applications': {
      id: '/_app/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof AppMyApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMyApplicationsRoute: typeof AppMyApplicationsRoute
  AppNewApplicationRoute: typeof AppNewApplicationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMyApplicationsRoute: AppMyApplicationsRoute,
  AppNewApplicationRoute: AppNewApplicationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
